name = "sync-counts"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/15 * * * *"]  # every 15 minutes

[[kv_namespaces]]
binding = "COUNTS_KV"
id = "15d97bbfce4842aea2e15817010aeb58"

[vars]
AWS_REGION = "us-east-1"
DYNAMODB_TABLE = "leagueql-table-prod"

[observability.logs]
enabled = true
invocation_logs = true

# Secrets set via CLI
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY