name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: Set GitHub Actions Role
    runs-on: ubuntu-latest
    outputs:
      role-arn: ${{ steps.set-role.outputs.role-arn }}

    steps:
      - name: Set Role Based on Event Type
        id: set-role
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "role-arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-dev-role" >> $GITHUB_OUTPUT
          else
            echo "role-arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-prod-role" >> $GITHUB_OUTPUT
          fi

  deploy:
    # TODO: change this step name to dynamically append env
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.setup.outputs.role-arn }}
          aws-region: us-east-1
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity
